baseurl = "https://limingxie.github.io/"
languageCode = "en-us"
title = "宅男 + 屌丝 + 程序员"
theme = "mainroad"
paginate = "10" # Number of posts per page
# disqusShortname = "" # Enable comments by entering your Disqus shortname
# googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author] # Used in authorbox
  name = "李明燮(li_mingxie)"
  bio = "宅男 + 屌丝 + 程序员"
  avatar = "images/limingxie2.jpeg"

[Params]
  description = "宅男 + 屌丝 + 程序员" # Site description. Used in meta description
  copyright = "李明燮(li_mingxie)  email:li_mingxie@163.com" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = false # Enable Twitter Cards if true
  readmore = false # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["algorithm","database","etc","go","java","js","limingxie","network","system"] # Specify section pages to show on home page and the "Recent articles" widget
  dateformat = "2006-01-02" # Change the format of dates
  mathjax = true # Enable MathJax
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  # customCSS = ["css/custom.css"] # Include custom CSS files
  # customJS = ["js/custom.js"] # Include custom JS files

  # DEPRECATED PARAMS
  subtitle = "js" # Deprecated in favor of .Site.Params.logo.subtitle
  highlightColor = "js" # Deprecated in favor of .Site.Params.style.vars.highlightColor

[Params.style.vars]
  highlightColor = "#e22d30" # Override highlight color

  # Override font-family sets
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  # Secondary font-family set responsible for pre, code, kbd, and samp tags font
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "images/limingxie2.jpeg" # Logo image. Path relative to "static"
  title = "李明燮(li_mingxie)_Blog" # Logo title, otherwise will use site title
  subtitle = "宅男 + 屌丝 + 程序员" # Logo subtitle

[Params.thumbnail]
  visibility = ["list", "post"] # Control thumbnail visibility

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 6 # Set the number of articles in the "Recent articles" widget
  categories_counter = true # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  # facebook = "username"
  # twitter = "username"
  # instagram = "username"
  # linkedin = "username"
  # telegram = "username"
  github = "limingxie"
  # gitlab = "username"
  # bitbucket = "username"
  email = "li_mingxie@163.com"

# Custom social links

[[Params.widgets.social.custom]]
  title = "简书"
  url = "https://www.jianshu.com/u/93eee2dde88b"


## Menu items

[menu]
  [[menu.main]]
  name = "Home"
  identifier = "Home"
  weight = 100
  url = "/"

[[menu.main]]
  name = "随笔"
  identifier = "随笔"
  weight = 200
  url = "/limingxie/"

  [[menu.main]]
  name = "Golang"
  weight = 300
  identifier = "Golang"
  url = "/go/"

  [[menu.main]]
  name = "Java"
  weight = 400
  identifier = "Java"
  url = "/java/"

  [[menu.main]]
  name = "js相关"
  weight = 500
  identifier = "js相关"
  url = "/js/"

  [[menu.main]]
  name = "系统环境"
  weight = 600
  identifier = "系统环境"
  url = "/system/"

  [[menu.main]]
  name = "database"
  weight = 700
  identifier = "database"
  url = "/database/"

  [[menu.main]]
  name = "算法"
  weight = 800
  identifier = "算法"
  url = "/algorithm/"

  [[menu.main]]
  name = "其它"
  weight = 900
  identifier = "其它"
  url = "/etc/"